---
- name: Deploy Docker to Host
  hosts: all
  become: yes
  # vars:
    # pip_install_packages:
      # - name: docker
      # - name: docker-compose
  tasks:
    - name: Install docker
      include_role:
        name: geerlingguy.docker
      vars:
        docker_install_compose: true
        docker_compose_version: 'v2.27.0'
        docker_compose_arch: "{{ ansible_architecture }}"
        docker_compose_path: /usr/local/bin/docker-compose
    - name: Install Packges
      include_role:
        name: geerlingguy.pip
