
services:

  # App Service
  app:
    image: anzeha/sampleapp:latest
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.new_app.rule=Host(`newapp.habjan.freemyip.com`)
      - traefik.http.routers.new_app.entrypoints=websecure
      - traefik.http.routers.new_app.tls.certresolver=letsencrypt
      - traefik.http.routers.new_app.service=new_app_svc
      - traefik.http.services.new_app_svc.loadBalancer.server.port=8080
    depends_on: 
      - redis # This service depends on redis. Start that first.
    environment: # Pass environment variables to the service
      REDIS_URL: redis:6379    
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - traefik

  # Redis Service   
  redis:
    image: "redis:alpine" # Use a public Redis image to build the redis service    
    restart: unless-stopped
    networks:
      - traefik

networks:
  traefik:
    external:
      name: web